#ifndef NFLY_GROUPS_H
#define NFLY_GROUPS_H

/* FlyWire group IDs from the pinned upstream neuron_meta.json. */
typedef enum {
    NF_G_VIS_R1R6 = 0,
    NF_G_VIS_R7R8 = 1,
    NF_G_VIS_ME = 2,
    NF_G_VIS_LO = 3,
    NF_G_VIS_LC = 4,
    NF_G_VIS_LPTC = 5,
    NF_G_OLF_ORN_FOOD = 6,
    NF_G_OLF_ORN_DANGER = 7,
    NF_G_OLF_LN = 8,
    NF_G_OLF_PN = 9,
    NF_G_MECH_BRISTLE = 10,
    NF_G_MECH_JO = 11,
    NF_G_MECH_CHORD = 12,
    NF_G_ANTENNAL_MECH = 13,
    NF_G_THERMO_WARM = 14,
    NF_G_THERMO_COOL = 15,
    NF_G_NOCI = 16,
    NF_G_MB_KC = 17,
    NF_G_MB_APL = 18,
    NF_G_MB_MBON_APP = 19,
    NF_G_MB_MBON_AV = 20,
    NF_G_MB_DAN_REW = 21,
    NF_G_MB_DAN_PUN = 22,
    NF_G_LH_APP = 23,
    NF_G_LH_AV = 24,
    NF_G_CX_EPG = 25,
    NF_G_CX_PFN = 26,
    NF_G_CX_FC = 27,
    NF_G_CX_HDELTA = 28,
    NF_G_SEZ_FEED = 29,
    NF_G_SEZ_GROOM = 30,
    NF_G_SEZ_WATER = 31,
    NF_G_GUS_GRN_SWEET = 32,
    NF_G_GUS_GRN_BITTER = 33,
    NF_G_GUS_GRN_WATER = 34,
    NF_G_GNG_DESC = 35,
    NF_G_CLOCK_DN = 36,
    NF_G_DRIVE_HUNGER = 37,
    NF_G_DRIVE_FEAR = 38,
    NF_G_DRIVE_FATIGUE = 39,
    NF_G_DRIVE_CURIOSITY = 40,
    NF_G_DRIVE_GROOM = 41,
    NF_G_DN_WALK = 42,
    NF_G_DN_FLIGHT = 43,
    NF_G_DN_TURN = 44,
    NF_G_DN_BACKUP = 45,
    NF_G_DN_STARTLE = 46,
    NF_G_VNC_CPG = 47,
    NF_G_MN_LEG_L1 = 48,
    NF_G_MN_LEG_R1 = 49,
    NF_G_MN_LEG_L2 = 50,
    NF_G_MN_LEG_R2 = 51,
    NF_G_MN_LEG_L3 = 52,
    NF_G_MN_LEG_R3 = 53,
    NF_G_MN_WING_L = 54,
    NF_G_MN_WING_R = 55,
    NF_G_MN_PROBOSCIS = 56,
    NF_G_MN_HEAD = 57,
    NF_G_MN_ABDOMEN = 58,
    NF_G_GENERIC_SENSORY = 59,
    NF_G_GENERIC_CENTRAL = 60,
    NF_G_GENERIC_DRIVES = 61,
    NF_G_GENERIC_MOTOR = 62,
    NF_GROUP_COUNT = 63
} NFGroup;

extern const char *const nf_group_names[NF_GROUP_COUNT];
extern const unsigned char nf_group_regions[NF_GROUP_COUNT];

#endif
